# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lalinhe_bridge.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1850, 950)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Main_stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.Main_stackedWidget.setGeometry(QtCore.QRect(200, 100, 1641, 871))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.Main_stackedWidget.setFont(font)
        self.Main_stackedWidget.setObjectName("Main_stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 50, 871, 421))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.page1_vlayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.page1_vlayout.setContentsMargins(0, 0, 0, 0)
        self.page1_vlayout.setObjectName("page1_vlayout")
        self.page1_widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.page1_widget.setFont(font)
        self.page1_widget.setObjectName("page1_widget")
        self.page1_vlayout.addWidget(self.page1_widget)
        self.page1_tabwidget = QtWidgets.QTabWidget(self.page)
        self.page1_tabwidget.setGeometry(QtCore.QRect(1030, 60, 541, 361))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(11)
        self.page1_tabwidget.setFont(font)
        self.page1_tabwidget.setObjectName("page1_tabwidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pg1_tab_zhdm_lb = QtWidgets.QLabel(self.tab)
        self.pg1_tab_zhdm_lb.setEnabled(True)
        self.pg1_tab_zhdm_lb.setGeometry(QtCore.QRect(10, -1, 521, 251))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(11)
        self.pg1_tab_zhdm_lb.setFont(font)
        self.pg1_tab_zhdm_lb.setObjectName("pg1_tab_zhdm_lb")
        self.kz_strain_dc = QtWidgets.QLabel(self.tab)
        self.kz_strain_dc.setGeometry(QtCore.QRect(270, 120, 10, 10))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(11)
        self.kz_strain_dc.setFont(font)
        self.kz_strain_dc.setObjectName("kz_strain_dc")
        self.kz_strain_pc = QtWidgets.QLabel(self.tab)
        self.kz_strain_pc.setGeometry(QtCore.QRect(270, 190, 10, 10))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(11)
        self.kz_strain_pc.setFont(font)
        self.kz_strain_pc.setObjectName("kz_strain_pc")
        self.kz_strain_pl = QtWidgets.QLabel(self.tab)
        self.kz_strain_pl.setGeometry(QtCore.QRect(190, 190, 10, 10))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(11)
        self.kz_strain_pl.setFont(font)
        self.kz_strain_pl.setObjectName("kz_strain_pl")
        self.kz_strain_pr = QtWidgets.QLabel(self.tab)
        self.kz_strain_pr.setGeometry(QtCore.QRect(350, 190, 10, 10))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(11)
        self.kz_strain_pr.setFont(font)
        self.kz_strain_pr.setObjectName("kz_strain_pr")
        self.page1_tabwidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pg1_tab_zdm_lb = QtWidgets.QLabel(self.tab_2)
        self.pg1_tab_zdm_lb.setEnabled(True)
        self.pg1_tab_zdm_lb.setGeometry(QtCore.QRect(10, -1, 521, 251))
        self.pg1_tab_zdm_lb.setObjectName("pg1_tab_zdm_lb")
        self.kr_strain_dcl = QtWidgets.QLabel(self.tab_2)
        self.kr_strain_dcl.setGeometry(QtCore.QRect(220, 120, 10, 10))
        self.kr_strain_dcl.setObjectName("kr_strain_dcl")
        self.kr_strain_dcr = QtWidgets.QLabel(self.tab_2)
        self.kr_strain_dcr.setGeometry(QtCore.QRect(320, 120, 10, 10))
        self.kr_strain_dcr.setObjectName("kr_strain_dcr")
        self.kr_strain_pc = QtWidgets.QLabel(self.tab_2)
        self.kr_strain_pc.setGeometry(QtCore.QRect(270, 190, 10, 10))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(11)
        self.kr_strain_pc.setFont(font)
        self.kr_strain_pc.setObjectName("kr_strain_pc")
        self.kr_strain_dl = QtWidgets.QLabel(self.tab_2)
        self.kr_strain_dl.setGeometry(QtCore.QRect(170, 120, 10, 10))
        self.kr_strain_dl.setObjectName("kr_strain_dl")
        self.kr_strain_dr = QtWidgets.QLabel(self.tab_2)
        self.kr_strain_dr.setGeometry(QtCore.QRect(370, 120, 10, 10))
        self.kr_strain_dr.setObjectName("kr_strain_dr")
        self.kr_strain_dc = QtWidgets.QLabel(self.tab_2)
        self.kr_strain_dc.setGeometry(QtCore.QRect(270, 120, 10, 10))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(11)
        self.kr_strain_dc.setFont(font)
        self.kr_strain_dc.setObjectName("kr_strain_dc")
        self.page1_tabwidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pg1_tab_ydm_lb = QtWidgets.QLabel(self.tab_3)
        self.pg1_tab_ydm_lb.setEnabled(True)
        self.pg1_tab_ydm_lb.setGeometry(QtCore.QRect(10, -1, 521, 251))
        self.pg1_tab_ydm_lb.setObjectName("pg1_tab_ydm_lb")
        self.kl_strain_dl = QtWidgets.QLabel(self.tab_3)
        self.kl_strain_dl.setGeometry(QtCore.QRect(170, 120, 10, 10))
        self.kl_strain_dl.setObjectName("kl_strain_dl")
        self.kl_strain_dr = QtWidgets.QLabel(self.tab_3)
        self.kl_strain_dr.setGeometry(QtCore.QRect(370, 120, 10, 10))
        self.kl_strain_dr.setObjectName("kl_strain_dr")
        self.kl_strain_dc = QtWidgets.QLabel(self.tab_3)
        self.kl_strain_dc.setGeometry(QtCore.QRect(270, 120, 10, 10))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(11)
        self.kl_strain_dc.setFont(font)
        self.kl_strain_dc.setObjectName("kl_strain_dc")
        self.kl_strain_pc = QtWidgets.QLabel(self.tab_3)
        self.kl_strain_pc.setGeometry(QtCore.QRect(270, 190, 10, 10))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(11)
        self.kl_strain_pc.setFont(font)
        self.kl_strain_pc.setObjectName("kl_strain_pc")
        self.page1_tabwidget.addTab(self.tab_3, "")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(99, 490, 901, 281))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.verticalLayoutWidget_2.setFont(font)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.page1_vl_graph = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.page1_vl_graph.setContentsMargins(0, 0, 0, 0)
        self.page1_vl_graph.setObjectName("page1_vl_graph")
        self.pg1_cn1 = QtWidgets.QLabel(self.page)
        self.pg1_cn1.setGeometry(QtCore.QRect(80, 40, 50, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.pg1_cn1.setFont(font)
        self.pg1_cn1.setObjectName("pg1_cn1")
        self.pg1_cn2 = QtWidgets.QLabel(self.page)
        self.pg1_cn2.setGeometry(QtCore.QRect(940, 40, 50, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.pg1_cn2.setFont(font)
        self.pg1_cn2.setObjectName("pg1_cn2")
        self.pg1_cn3 = QtWidgets.QLabel(self.page)
        self.pg1_cn3.setGeometry(QtCore.QRect(80, 440, 50, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.pg1_cn3.setFont(font)
        self.pg1_cn3.setObjectName("pg1_cn3")
        self.pg1_cn4 = QtWidgets.QLabel(self.page)
        self.pg1_cn4.setGeometry(QtCore.QRect(940, 440, 50, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.pg1_cn4.setFont(font)
        self.pg1_cn4.setObjectName("pg1_cn4")
        self.line = QtWidgets.QFrame(self.page)
        self.line.setGeometry(QtCore.QRect(150, 42, 771, 2))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.page)
        self.line_2.setGeometry(QtCore.QRect(150, 484, 771, 2))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pg1_cn1_2 = QtWidgets.QLabel(self.page)
        self.pg1_cn1_2.setGeometry(QtCore.QRect(80, 510, 50, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.pg1_cn1_2.setFont(font)
        self.pg1_cn1_2.setObjectName("pg1_cn1_2")
        self.pg1_cn2_2 = QtWidgets.QLabel(self.page)
        self.pg1_cn2_2.setGeometry(QtCore.QRect(940, 510, 50, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.pg1_cn2_2.setFont(font)
        self.pg1_cn2_2.setObjectName("pg1_cn2_2")
        self.pg1_cn3_2 = QtWidgets.QLabel(self.page)
        self.pg1_cn3_2.setGeometry(QtCore.QRect(80, 730, 50, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.pg1_cn3_2.setFont(font)
        self.pg1_cn3_2.setObjectName("pg1_cn3_2")
        self.pg1_cn4_2 = QtWidgets.QLabel(self.page)
        self.pg1_cn4_2.setGeometry(QtCore.QRect(940, 730, 50, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.pg1_cn4_2.setFont(font)
        self.pg1_cn4_2.setObjectName("pg1_cn4_2")
        self.line_3 = QtWidgets.QFrame(self.page)
        self.line_3.setGeometry(QtCore.QRect(150, 513, 771, 2))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.page)
        self.line_4.setGeometry(QtCore.QRect(150, 775, 771, 2))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_10 = QtWidgets.QFrame(self.page)
        self.line_10.setGeometry(QtCore.QRect(984, 110, 2, 311))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.line_10.setFont(font)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_9 = QtWidgets.QFrame(self.page)
        self.line_9.setGeometry(QtCore.QRect(82, 110, 2, 311))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.line_9.setFont(font)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_11 = QtWidgets.QFrame(self.page)
        self.line_11.setGeometry(QtCore.QRect(82, 580, 2, 131))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.line_11.setFont(font)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.page)
        self.line_12.setGeometry(QtCore.QRect(984, 580, 2, 131))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.line_12.setFont(font)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.pg1_cn1_3 = QtWidgets.QLabel(self.page)
        self.pg1_cn1_3.setGeometry(QtCore.QRect(1010, 40, 50, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.pg1_cn1_3.setFont(font)
        self.pg1_cn1_3.setObjectName("pg1_cn1_3")
        self.pg1_cn2_3 = QtWidgets.QLabel(self.page)
        self.pg1_cn2_3.setGeometry(QtCore.QRect(1540, 40, 50, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.pg1_cn2_3.setFont(font)
        self.pg1_cn2_3.setObjectName("pg1_cn2_3")
        self.pg1_cn3_3 = QtWidgets.QLabel(self.page)
        self.pg1_cn3_3.setGeometry(QtCore.QRect(1010, 730, 50, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.pg1_cn3_3.setFont(font)
        self.pg1_cn3_3.setObjectName("pg1_cn3_3")
        self.pg1_cn4_3 = QtWidgets.QLabel(self.page)
        self.pg1_cn4_3.setGeometry(QtCore.QRect(1540, 730, 50, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.pg1_cn4_3.setFont(font)
        self.pg1_cn4_3.setObjectName("pg1_cn4_3")
        self.line_13 = QtWidgets.QFrame(self.page)
        self.line_13.setGeometry(QtCore.QRect(1080, 42, 441, 2))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.line_13.setFont(font)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.page)
        self.line_14.setGeometry(QtCore.QRect(1080, 775, 441, 2))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.line_14.setFont(font)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.page)
        self.line_15.setGeometry(QtCore.QRect(1584, 110, 2, 601))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.line_15.setFont(font)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.page)
        self.line_16.setGeometry(QtCore.QRect(1012, 110, 2, 601))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.line_16.setFont(font)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(1029, 439, 541, 321))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.pg1_camlb = QtWidgets.QLabel(self.groupBox)
        self.pg1_camlb.setGeometry(QtCore.QRect(10, 40, 351, 261))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(11)
        self.pg1_camlb.setFont(font)
        self.pg1_camlb.setObjectName("pg1_camlb")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(380, 40, 101, 21))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(380, 80, 101, 21))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(380, 120, 101, 21))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.strain_lb = QtWidgets.QLabel(self.page)
        self.strain_lb.setGeometry(QtCore.QRect(1070, 340, 21, 21))
        self.strain_lb.setObjectName("strain_lb")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(1100, 340, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.page1_selectsensorlb = QtWidgets.QLabel(self.page)
        self.page1_selectsensorlb.setGeometry(QtCore.QRect(1051, 140, 491, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.page1_selectsensorlb.setFont(font)
        self.page1_selectsensorlb.setAlignment(QtCore.Qt.AlignCenter)
        self.page1_selectsensorlb.setObjectName("page1_selectsensorlb")
        self.page1_selectbridgelb = QtWidgets.QLabel(self.page)
        self.page1_selectbridgelb.setGeometry(QtCore.QRect(1050, 100, 501, 31))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(14)
        self.page1_selectbridgelb.setFont(font)
        self.page1_selectbridgelb.setAlignment(QtCore.Qt.AlignCenter)
        self.page1_selectbridgelb.setObjectName("page1_selectbridgelb")
        self.pg1_cn2_3.raise_()
        self.pg1_cn1_3.raise_()
        self.page1_tabwidget.raise_()
        self.pg1_cn3_3.raise_()
        self.pg1_cn4_3.raise_()
        self.pg1_cn3.raise_()
        self.pg1_cn4.raise_()
        self.pg1_cn2.raise_()
        self.pg1_cn1.raise_()
        self.verticalLayoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.pg1_cn1_2.raise_()
        self.pg1_cn3_2.raise_()
        self.pg1_cn4_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.line_10.raise_()
        self.line_9.raise_()
        self.line_11.raise_()
        self.line_12.raise_()
        self.line_13.raise_()
        self.line_14.raise_()
        self.line_15.raise_()
        self.line_16.raise_()
        self.groupBox.raise_()
        self.strain_lb.raise_()
        self.pg1_cn2_2.raise_()
        self.label_2.raise_()
        self.page1_selectsensorlb.raise_()
        self.page1_selectbridgelb.raise_()
        self.Main_stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.Main_stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pushButton = QtWidgets.QPushButton(self.page_2)
        self.pushButton.setGeometry(QtCore.QRect(60, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.Main_stackedWidget.addWidget(self.page_2)
        self.MainMenu_miBtn = QtWidgets.QPushButton(self.centralwidget)
        self.MainMenu_miBtn.setGeometry(QtCore.QRect(30, 160, 211, 71))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(20)
        self.MainMenu_miBtn.setFont(font)
        self.MainMenu_miBtn.setObjectName("MainMenu_miBtn")
        self.MainMenu_rtdBtn = QtWidgets.QPushButton(self.centralwidget)
        self.MainMenu_rtdBtn.setGeometry(QtCore.QRect(30, 240, 211, 71))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(20)
        self.MainMenu_rtdBtn.setFont(font)
        self.MainMenu_rtdBtn.setObjectName("MainMenu_rtdBtn")
        self.MainMenu_dnBtn = QtWidgets.QPushButton(self.centralwidget)
        self.MainMenu_dnBtn.setGeometry(QtCore.QRect(30, 320, 211, 71))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(20)
        self.MainMenu_dnBtn.setFont(font)
        self.MainMenu_dnBtn.setObjectName("MainMenu_dnBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 30, 1051, 71))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cn1 = QtWidgets.QLabel(self.centralwidget)
        self.cn1.setGeometry(QtCore.QRect(10, 140, 50, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.cn1.setFont(font)
        self.cn1.setObjectName("cn1")
        self.cn2 = QtWidgets.QLabel(self.centralwidget)
        self.cn2.setGeometry(QtCore.QRect(210, 140, 50, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.cn2.setFont(font)
        self.cn2.setObjectName("cn2")
        self.cn3 = QtWidgets.QLabel(self.centralwidget)
        self.cn3.setGeometry(QtCore.QRect(10, 540, 50, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.cn3.setFont(font)
        self.cn3.setObjectName("cn3")
        self.cn4 = QtWidgets.QLabel(self.centralwidget)
        self.cn4.setGeometry(QtCore.QRect(210, 540, 50, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.cn4.setFont(font)
        self.cn4.setObjectName("cn4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(77, 142, 111, 2))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.line_5.setFont(font)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(77, 584, 118, 2))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.line_6.setFont(font)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(12, 210, 2, 311))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.line_7.setFont(font)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(254, 210, 2, 311))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.main_giflb = QtWidgets.QLabel(self.centralwidget)
        self.main_giflb.setGeometry(QtCore.QRect(1670, 10, 111, 111))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.main_giflb.setFont(font)
        self.main_giflb.setObjectName("main_giflb")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(880, 30, 331, 71))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.lcdNumber.setFont(font)
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber.setDigitCount(8)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(1230, 30, 361, 71))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        self.lcdNumber_2.setFont(font)
        self.lcdNumber_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_2.setDigitCount(10)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.Main_stackedWidget.raise_()
        self.MainMenu_rtdBtn.raise_()
        self.label.raise_()
        self.cn1.raise_()
        self.cn2.raise_()
        self.MainMenu_miBtn.raise_()
        self.cn3.raise_()
        self.cn4.raise_()
        self.MainMenu_dnBtn.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.line_8.raise_()
        self.line_7.raise_()
        self.main_giflb.raise_()
        self.lcdNumber.raise_()
        self.lcdNumber_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1850, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionlink_DB = QtWidgets.QAction(MainWindow)
        self.actionlink_DB.setObjectName("actionlink_DB")
        self.menu_2.addAction(self.actionlink_DB)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.Main_stackedWidget.setCurrentIndex(0)
        self.page1_tabwidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pg1_tab_zhdm_lb.setText(_translate("MainWindow", "TextLabel"))
        self.kz_strain_dc.setText(_translate("MainWindow", "TextLabel"))
        self.kz_strain_pc.setText(_translate("MainWindow", "TextLabel"))
        self.kz_strain_pl.setText(_translate("MainWindow", "TextLabel"))
        self.kz_strain_pr.setText(_translate("MainWindow", "TextLabel"))
        self.page1_tabwidget.setTabText(self.page1_tabwidget.indexOf(self.tab), _translate("MainWindow", "跨中截面"))
        self.pg1_tab_zdm_lb.setText(_translate("MainWindow", "TextLabel"))
        self.kr_strain_dcl.setText(_translate("MainWindow", "TextLabel"))
        self.kr_strain_dcr.setText(_translate("MainWindow", "TextLabel"))
        self.kr_strain_pc.setText(_translate("MainWindow", "TextLabel"))
        self.kr_strain_dl.setText(_translate("MainWindow", "TextLabel"))
        self.kr_strain_dr.setText(_translate("MainWindow", "TextLabel"))
        self.kr_strain_dc.setText(_translate("MainWindow", "TextLabel"))
        self.page1_tabwidget.setTabText(self.page1_tabwidget.indexOf(self.tab_2), _translate("MainWindow", "跨北截面"))
        self.pg1_tab_ydm_lb.setText(_translate("MainWindow", "TextLabel"))
        self.kl_strain_dl.setText(_translate("MainWindow", "TextLabel"))
        self.kl_strain_dr.setText(_translate("MainWindow", "TextLabel"))
        self.kl_strain_dc.setText(_translate("MainWindow", "TextLabel"))
        self.kl_strain_pc.setText(_translate("MainWindow", "TextLabel"))
        self.page1_tabwidget.setTabText(self.page1_tabwidget.indexOf(self.tab_3), _translate("MainWindow", "跨南截面"))
        self.pg1_cn1.setText(_translate("MainWindow", "TextLabel"))
        self.pg1_cn2.setText(_translate("MainWindow", "TextLabel"))
        self.pg1_cn3.setText(_translate("MainWindow", "TextLabel"))
        self.pg1_cn4.setText(_translate("MainWindow", "TextLabel"))
        self.pg1_cn1_2.setText(_translate("MainWindow", "TextLabel"))
        self.pg1_cn2_2.setText(_translate("MainWindow", "TextLabel"))
        self.pg1_cn3_2.setText(_translate("MainWindow", "TextLabel"))
        self.pg1_cn4_2.setText(_translate("MainWindow", "TextLabel"))
        self.pg1_cn1_3.setText(_translate("MainWindow", "TextLabel"))
        self.pg1_cn2_3.setText(_translate("MainWindow", "TextLabel"))
        self.pg1_cn3_3.setText(_translate("MainWindow", "TextLabel"))
        self.pg1_cn4_3.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox.setTitle(_translate("MainWindow", "现场概况"))
        self.pg1_camlb.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "桥长：400m"))
        self.label_4.setText(_translate("MainWindow", "环境温度："))
        self.label_5.setText(_translate("MainWindow", "运行状况："))
        self.strain_lb.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "应变传感器"))
        self.page1_selectsensorlb.setText(_translate("MainWindow", "尚未选择传感器"))
        self.page1_selectbridgelb.setText(_translate("MainWindow", "尚未选择桥跨"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.MainMenu_miBtn.setText(_translate("MainWindow", "实时数据"))
        self.MainMenu_rtdBtn.setText(_translate("MainWindow", "历史数据"))
        self.MainMenu_dnBtn.setText(_translate("MainWindow", "结构诊断"))
        self.label.setText(_translate("MainWindow", "拉林河大桥智能在线监测系统"))
        self.cn1.setText(_translate("MainWindow", "TextLabel"))
        self.cn2.setText(_translate("MainWindow", "TextLabel"))
        self.cn3.setText(_translate("MainWindow", "TextLabel"))
        self.cn4.setText(_translate("MainWindow", "TextLabel"))
        self.main_giflb.setText(_translate("MainWindow", "TextLabel"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "连接"))
        self.menu_3.setTitle(_translate("MainWindow", "关于"))
        self.actionlink_DB.setText(_translate("MainWindow", "link DB"))
